name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install
        run: pip install -r requirements-test.txt .

      - name: Test
        run: pytest tests/ -v
